name: CI - Codecov

on:
  push:
    branches: [ "main", "master" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Cambia a la versión de Python que necesites

      # 3. Instala dependencias
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install coverage

      # 4. Ejecuta tests con unittest y coverage
      - name: Run tests with coverage
        run: coverage run -m unittest discover

      # 5. Sube el reporte a Codecov
      - name: Upload coverage to Codecov
        run: |
          pip install codecov
          codecov --token=${{ secrets.CODECOV_TOKEN }}
