name: CI - Codecov

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'  # Cambia a la versión de Python que necesites

      # 3. (Opcional) Configura PYTHONPATH
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/MyAdventures" >> $GITHUB_ENV

      # 4. Instala dependencias
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install coverage
          pip install mcpi
          pip install pyserial
          pip install simpleserial

      # 5. Ejecuta tests con coverage, ignorando errores de hardware (|| true)
      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover -s MyAdventures || true
          coverage xml -o coverage2.xml

      # 6. Sube el reporte a Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage2.xml
          flags: unittests
          name: codecov-umbrella


